export const WORKSPACE_NAME_MAX_LENGTH = 100;
export const WORKSPACE_COUNTRY_MAX_LENGTH = 50;
export const WORKSPACE_CITY_MAX_LENGTH = 100;
export const WORKSPACE_STREET_MAX_LENGTH = 100;
export const WORKSPACE_STREET_NUMBER_MAX_LENGTH = 50;
export const WORKSPACE_POSTAL_CODE_MAX_LENGTH = 100;

export const GET_WORKSPACES_SEARCH_MAX_LENGTH = 200;
export const GET_WORKSPACES_DEFAULT_LIMIT = 50;
export const GET_WORKSPACES_MAX_LIMIT = 100;
